apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-access
  namespace: default
spec:
  # 将此策略应用于您的 webhook pod
  podSelector:
    matchLabels:
      app: webhook-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow traffic from any pod with the "component: kube-apiserver" label
        # from any namespace.
        - podSelector:
            matchLabels:
              component: kube-apiserver
      ports:
        - protocol: TCP
          port: 443 # Webhook 服务监听的端口
