apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-demo
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    server {
      listen 8080;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }