log_level: "debug"
prow:
  prowjob_namespace: "default"
  pod_namespace: "default"
  plank:
    job_url_template: "https://deck.prow.moicen.com/view/{{.Spec.Job}}/{{.Status.BuildID}}"
    default_decoration_configs:
      "*":
        timeout: "2h"
        grace_period: "15s"
        utility_images:
          clonerefs: "gcr.io/k8s-prow/clonerefs:latest"
          initupload: "gcr.io/k8s-prow/initupload:latest"
          entrypoint: "gcr.io/k8s-prow/entrypoint:latest"
          sidecar: "gcr.io/k8s-prow/sidecar:latest"
        gcs_configuration:
          bucket: "prow-artifacts"
          path_strategy: "explicit"
          default_org: "liweinan"
          default_repo: "my-prow-test-proj"
  github:
    app_id: "1263514"
    app_private_key_path: "/etc/github/github-token"
    hook_url: "https://hook.prow.moicen.com/hook"
    hmac_secret_file: "/etc/hmac/hmac"
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 5m
  deck:
    deck_instances: 1
    spyglass:
      size_limit: 100000000
  tide:
    queries:
      - repos:
          - liweinan/my-prow-test-proj
        labels:
          - lgtm
          - approved
        missingLabels:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - do-not-merge/invalid-owners-file
        reviewApprovedRequired: true
  sinker:
    resync_period: 1h
    max_prowjob_age: 168h
    max_pod_age: 24h
  trigger:
    trusted_apps:
      - liweinan/my-prow-test-proj
    join_org_url: https://github.com/orgs/liweinan/people