prow:
  log_level: "debug"
  prowjob_namespace: "prow"
  pod_namespace: "prow"
  plank:
    job_url_template: 'https://prow.example.com/view/{{.Spec.Job}}/{{.Status.BuildID}}'
  hook:
    bind_address: "0.0.0.0:8888"
    github_app_id: "1263514"
    github_app_private_key_path: "/etc/github/github-token"
    hmac_token_path: "/etc/hmac/hmac"
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 5m
  deck:  # Restore Deck configuration
    deck_instances: 1
    spyglass:
      size_limit: 100000000
