# Role to grant permissions to access ProwJob resources in the prow namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prow-deck
  namespace: prow
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["get", "list", "watch"]

---
# RoleBinding to bind the Role to the default ServiceAccount in the prow namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prow-deck
  namespace: prow
subjects:
- kind: ServiceAccount
  name: default
  namespace: prow
roleRef:
  kind: Role
  name: prow-deck
  apiGroup: rbac.authorization.k8s.io
