apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes/test-infra/pull/8669
spec:
  group: prow.k8s.io
  names:
    kind: ProwJob
    listKind: ProwJobList
    plural: prowjobs
    singular: prowjob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - presubmit
                    - postsubmit
                    - periodic
                    - batch
                job:
                  type: string
                agent:
                  type: string
                cluster:
                  type: string
                namespace:
                  type: string
                context:
                  type: string
                max_concurrency:
                  type: integer
                rerun_command:
                  type: string
                report:
                  type: boolean
                decoration_config:
                  type: object
                  properties:
                    timeout:
                      description: |
                        Timeout is how long the pod utilities will wait before aborting a job with SIGINT.
                      anyOf:
                        - type: integer
                        - type: string
                      x-kubernetes-int-or-string: true
                    grace_period:
                      description: |
                        GracePeriod is how long the pod utilities will wait after sending SIGINT to send SIGKILL when aborting a job. Only applicable if decorating the PodSpec.
                      anyOf:
                        - type: integer
                        - type: string
                      x-kubernetes-int-or-string: true
                    gcs_configuration:
                      type: object
                      properties:
                        bucket:
                          type: string
                        path_strategy:
                          type: string
                        default_org:
                          type: string
                        default_repo:
                          type: string
                    utility_images:
                      type: object
                      properties:
                        clonerefs:
                          type: string
                        initupload:
                          type: string
                        entrypoint:
                          type: string
                        sidecar:
                          type: string
                refs:
                  type: object
                  properties:
                    org:
                      type: string
                    repo:
                      type: string
                    base_ref:
                      type: string
                    base_sha:
                      type: string
                    base_link:
                      type: string
                    repo_link:
                      type: string
                    pulls:
                      type: array
                      items:
                        type: object
                        properties:
                          number:
                            type: integer
                          author:
                            type: string
                          sha:
                            type: string
                          title:
                            type: string
                          link:
                            type: string
                          commit_link:
                            type: string
                          author_link:
                            type: string
                          head_ref:
                            type: string
                pod_spec:
                  type: object
                  properties:
                    containers:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          image:
                            type: string
                          command:
                            type: array
                            items:
                              type: string
                          args:
                            type: array
                            items:
                              type: string
                          resources:
                            type: object
                            properties:
                              requests:
                                type: object
                                properties:
                                  cpu:
                                    type: string
                                  memory:
                                    type: string
                              limits:
                                type: object
                                properties:
                                  cpu:
                                    type: string
                                  memory:
                                    type: string
                prowjob_defaults:
                  type: object
                  properties:
                    tenant_id:
                      type: string
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                    - triggered
                    - pending
                    - success
                    - failure
                    - aborted
                    - error
                startTime:
                  type: string
                  format: date-time
                completionTime:
                  type: string
                  format: date-time
                build_id:
                  type: string
                description:
                  type: string
                url:
                  type: string
                pod_name:
                  type: string
                pod_revival_count:
                  type: integer
      additionalPrinterColumns:
        - name: Job
          type: string
          jsonPath: .spec.job
        - name: BuildId
          type: string
          jsonPath: .status.build_id
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Org
          type: string
          jsonPath: .spec.refs.org
        - name: Repo
          type: string
          jsonPath: .spec.refs.repo
        - name: Pulls
          type: string
          jsonPath: .spec.refs.pulls[*].number
        - name: StartTime
          type: date
          jsonPath: .status.startTime
        - name: CompletionTime
          type: date
          jsonPath: .status.completionTime
        - name: State
          type: string
          jsonPath: .status.state
