apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prow-controller-manager
  labels:
    component: prow-controller-manager
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"] 