apiVersion: v1
kind: Pod
metadata:
  name: ba45ac4e-c992-4418-9277-6069c2004b2e
  namespace: default
spec:
  containers:
  - name: test
    image: golang:1.18
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    command: ["sleep", "infinity"]
