apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: test-job-$(date +%s)
  namespace: default
spec:
  type: presubmit
  agent: kubernetes
  cluster: default
  job: test-job
  refs:
    org: liweinan
    repo: my-prow-test-proj
    base_ref: main
    base_sha: abcdef1234567890abcdef1234567890abcdef12
    pulls:
      - number: 11
        author: liweinan
        sha: 1234567890abcdef1234567890abcdef12345678
  pod_spec:
    containers:
      - name: test
        image: golang:1.18
        command:
          - /bin/sh
          - -c
          - |
            echo "Working directory: $PWD"
            echo "Proxy settings:"
            echo "HTTP_PROXY=$HTTP_PROXY"
            echo "HTTPS_PROXY=$HTTPS_PROXY"
            echo "NO_PROXY=$NO_PROXY"
            sleep 3600
        env:
          - name: HTTP_PROXY
            value: "http://192.168.0.123:1080"
          - name: HTTPS_PROXY
            value: "http://192.168.0.123:1080"
          - name: NO_PROXY
            value: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.152.183.1"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
    serviceAccountName: plank