apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: test-unit-test-job
  namespace: default
  labels:
    prow.k8s.io/type: presubmit
    prow.k8s.io/job: unit-test
spec:
  type: presubmit
  agent: kubernetes
  cluster: default
  namespace: default
  job: unit-test
  refs:
    org: liweinan
    repo: my-prow-test-proj
    base_ref: main
    base_sha: "abcdef1234567890abcdef1234567890abcdef12"
    pulls:
    - number: 11
      author: liweinan
      sha: "1234567890abcdef1234567890abcdef12345678"
  pod_spec:
    containers:
      - image: golang:1.18
        command:
          - go
        args:
          - test
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
