apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: test-job-$(date +%s)   # Replace with a static name if not using shell preprocessing
  namespace: default
  labels:
    created-by-prow: "true"
    event-GUID: "test-event-guid"
    prow.k8s.io/context: unit-test
    prow.k8s.io/is-optional: "false"
    prow.k8s.io/job: unit-test
    prow.k8s.io/refs.base_ref: main
    prow.k8s.io/refs.org: liweinan
    prow.k8s.io/refs.pull: "11"
    prow.k8s.io/refs.repo: my-prow-test-proj
    prow.k8s.io/type: presubmit
  annotations:
    prow.k8s.io/context: unit-test
    prow.k8s.io/job: unit-test
spec:
  type: presubmit
  agent: kubernetes
  cluster: default
  context: unit-test
  job: unit-test
  max_concurrency: 10
  namespace: default
  report: true
  rerun_command: /test
  prowjob_defaults:
    tenant_id: GlobalDefaultID
  refs:
    base_link: https://github.com/liweinan/my-prow-test-proj/commit/8194af346733eeaf4fdf8eb5a10bdb6cc9ececcb
    base_ref: main
    base_sha: 8194af346733eeaf4fdf8eb5a10bdb6cc9ececcb
    org: liweinan
    pulls:
      - author: liweinan
        author_link: https://github.com/liweinan
        commit_link: https://github.com/liweinan/my-prow-test-proj/pull/11/commits/da7b31648afa980605533ea54b3079ea671a6929
        head_ref: test2
        link: https://github.com/liweinan/my-prow-test-proj/pull/11
        number: 11
        sha: da7b31648afa980605533ea54b3079ea671a6929
        title: test
    repo: my-prow-test-proj
    repo_link: https://github.com/liweinan/my-prow-test-proj
  pod_spec:
    containers:
      - name: test
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "Starting sleep..."
            sleep infinity
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
status:
  state: triggered
  startTime: "2024-05-15T07:10:18Z"