apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: test-job-$(date +%s)
  namespace: default
spec:
  type: presubmit
  agent: kubernetes
  cluster: default
  job: unit-test
  refs:
    org: liweinan
    repo: my-prow-test-proj
    base_ref: main
    base_sha: abcdef1234567890abcdef1234567890abcdef12
    pulls:
      - number: 11
        author: liweinan
        sha: 1234567890abcdef1234567890abcdef12345678
  pod_spec:
    containers:
      - name: test
        image: golang:1.18
        command:
          - /bin/sh
          - -c
          - |
            echo "Working directory: $PWD"
            echo "Proxy settings:"
            echo "HTTP_PROXY=$HTTP_PROXY"
            echo "HTTPS_PROXY=$HTTPS_PROXY"
            echo "NO_PROXY=$NO_PROXY"
            sleep 3600
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
  decoration_config:
    timeout: 1h
    grace_period: 15s
    utility_images:
      clonerefs: gcr.io/k8s-prow/clonerefs:latest
      initupload: gcr.io/k8s-prow/initupload:latest
      entrypoint: gcr.io/k8s-prow/entrypoint:latest
      sidecar: gcr.io/k8s-prow/sidecar:latest