apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: test-job-$(date +%s)
  namespace: default
spec:
  type: presubmit
  agent: kubernetes
  cluster: default
  job: unit-test
  refs:
    org: liweinan
    repo: my-prow-test-proj
    base_ref: main
    base_sha: abcdef1234567890abcdef1234567890abcdef12
    pulls:
      - number: 11
        author: liweinan
        sha: 1234567890abcdef1234567890abcdef12345678
  pod_spec:
    containers:
      - name: test
        image: golang:1.18
        command:
          - /bin/sh
        args:
          - -c
          - |
            echo "Working directory: $PWD"
            echo "Listing directory contents:"
            ls -R /go/src/github.com/liweinan/my-prow-test-proj
            echo "Checking file permissions:"
            ls -l /go/src/github.com/liweinan/my-prow-test-proj/go.mod || echo "go.mod not found"
            echo "Checking go.mod:"
            cat /go/src/github.com/liweinan/my-prow-test-proj/go.mod || echo "go.mod not readable"
            echo "Proxy settings:"
            echo "HTTP_PROXY=$HTTP_PROXY"
            echo "HTTPS_PROXY=$HTTPS_PROXY"
            echo "NO_PROXY=$NO_PROXY"
            echo "Go environment:"
            go env
            echo "Listing Go packages:"
            go list ./... || echo "No packages found"
            echo "Running go test recursive:"
            go test -v ./... || echo "go test failed, sleeping to debug..."
            sleep 30
        workingDir: "/go/src/github.com/liweinan/my-prow-test-proj"
        env:
          - name: HTTP_PROXY
            value: "http://192.168.0.123:1080"
          - name: HTTPS_PROXY
            value: "http://192.168.0.123:1080"
          - name: NO_PROXY
            value: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.152.183.1"
          - name: GO111MODULE
            value: "on"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
  decoration_config:
    timeout: 2h
    grace_period: 15s
    utility_images:
      clonerefs: gcr.io/k8s-prow/clonerefs:latest
      initupload: gcr.io/k8s-prow/initupload:latest
      entrypoint: gcr.io/k8s-prow/entrypoint:latest
      sidecar: gcr.io/k8s-prow/sidecar:latest
    gcs_configuration:
      bucket: "prow-artifacts"
      path_strategy: "explicit"
      default_org: "liweinan"
      default_repo: "my-prow-test-proj"